name: Generate DB and Create Release

on:
  schedule:
    - cron: '0 0 * * 0' # Run weekly on Sundays at midnight UTC
  workflow_dispatch: # Allows triggering the workflow manually from the GitHub UI

# Add permissions configuration
permissions:
  contents: write  # Required for creating releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install uv
        uses: astral-sh/setup-uv@v5
      
      - name: Install dependencies
        run: |
          uv pip install -r requirements.txt --system

      - name: Scrape Binder analytics data
        run: python launches/scrape_binder_analytics.py

      - name: Delete existing latest release
        run: |
          if [ -f "_build/launches.parquet" ] && [ $(stat -c%s "_build/launches.parquet" 2>/dev/null || stat -f%z "_build/launches.parquet") -gt 1000 ]; then
            gh release delete latest --yes || echo "No existing latest release to delete"
          else
            echo "Parquet file missing or too small, aborting to protect existing data"
            exit 1
          fi
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Release with Latest Data
        run: |
          CURRENT_DATE=$(date +'%Y-%m-%d')
          gh release create latest \
            --title "MyBinder Analytics Dataset" \
            --notes "Latest MyBinder analytics dataset updated on $CURRENT_DATE

          This release contains comprehensive MyBinder launch analytics data in parquet format.
          The data is updated weekly with any missing dates from the archive." \
            --latest \
            _build/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}